<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Alat;

class AlatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alats = [
            [
                'id' => 2,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-482686',
                'nama_alat' => 'Phase sequence',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '1 Buah',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => '01K3RAK1WDHA9GB4MK4YPAXAJJ.jpg',
                'created_at' => '2025-08-21 08:02:25',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 3,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-951870',
                'nama_alat' => 'Insulating',
                'kategori_alat' => 'pengukuran',
                'merek_alat' => '-',
                'spesifikasi' => '5000 - 10000 V',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-21 08:03:33',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 4,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-891728',
                'nama_alat' => 'Telescopic hotstick',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => '20 kV 10,5 Meter',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-21 08:05:26',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 5,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-116499',
                'nama_alat' => 'Tangga Fiber',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '2 section ladder (9,6 m)',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-21 08:07:12',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 6,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-229842',
                'nama_alat' => 'Groundcluster',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-21 08:08:16',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 7,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-217168',
                'nama_alat' => 'Strainging Device',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-21',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-21 08:09:58',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 8,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-880285',
                'nama_alat' => 'Hidrolik Press',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'dies uk 70 s.d mm2',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:36:43',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 9,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-811728',
                'nama_alat' => 'Hidrolik Press',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'dies uk 10 s.d 70 mm2',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:37:31',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 10,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-793418',
                'nama_alat' => 'Cable cutters',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:38:08',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 11,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-646070',
                'nama_alat' => 'Tool set',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'tools atau peralatan mobil',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:38:51',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 12,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-799201',
                'nama_alat' => 'Gergaji besi',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RCTQYCPD54ZNZRS3H61JMA.jpg',
                'created_at' => '2025-08-22 09:39:53',
                'updated_at' => '2025-08-28 06:10:48',
            ],
            [
                'id' => 13,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-123988',
                'nama_alat' => 'Palu',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '3-5 kg',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RCVGZERRHEDVVF0RNZHAZA.jpg',
                'created_at' => '2025-08-22 09:40:17',
                'updated_at' => '2025-08-28 06:11:13',
            ],
            [
                'id' => 14,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-195482',
                'nama_alat' => 'Tali',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => "bahan katun\n(U/ikat tangga) 10 meter",
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDRXYW84XWAEM21V6VM5XB.jpg',
                'created_at' => '2025-08-22 09:41:45',
                'updated_at' => '2025-08-28 06:27:17',
            ],
            [
                'id' => 15,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-537372',
                'nama_alat' => 'Lampu Senter',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'Rechargeable',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDADHH958XQPTEYWF5WWA7.jpg',
                'created_at' => '2025-08-22 09:42:23',
                'updated_at' => '2025-08-28 06:19:21',
            ],
            [
                'id' => 16,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-424244',
                'nama_alat' => 'Lampu Sorot',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '12 Volt 55 Watt',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:43:19',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 17,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-841968',
                'nama_alat' => 'Gadget',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RD8WGAJFNN45VHXSWG1ED3.jpg',
                'created_at' => '2025-08-22 09:43:51',
                'updated_at' => '2025-08-28 06:18:31',
            ],
            [
                'id' => 18,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-343542',
                'nama_alat' => 'Paket Data Aplikasi',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:44:24',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 19,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-331500',
                'nama_alat' => 'Charger HP Portable',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RD9JSB2FDKDWX26KT044S0.jpg',
                'created_at' => '2025-08-22 09:45:20',
                'updated_at' => '2025-08-28 06:18:54',
            ],
            [
                'id' => 20,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-390084',
                'nama_alat' => 'Branding Mobil',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:45:46',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 21,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-313589',
                'nama_alat' => 'Chainsaw Kecil',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RD3AENGXEKXZK5BXGS1W2G.jpg',
                'created_at' => '2025-08-22 09:46:14',
                'updated_at' => '2025-08-28 06:15:29',
            ],
            [
                'id' => 22,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-797519',
                'nama_alat' => 'Gunting Pengupas',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => 'pengupas kabel',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:46:48',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 23,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-341614',
                'nama_alat' => 'Bor tiang',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:47:26',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 24,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-544897',
                'nama_alat' => 'Band it',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'band it atau treck plate',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:48:17',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 25,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-822962',
                'nama_alat' => 'Parang',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:48:50',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 26,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-820624',
                'nama_alat' => 'Tang Ampere',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:49:16',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 27,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-732839',
                'nama_alat' => 'Radio mobile',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'radio digital',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RD7TJ491HCD57KE6V81H62.jpg',
                'created_at' => '2025-08-22 09:49:53',
                'updated_at' => '2025-08-28 06:17:56',
            ],
            [
                'id' => 28,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-281249',
                'nama_alat' => 'Arit Stick',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => 'PalmPro',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => 'foto-alat/01K3QHEY7MJPM63VWJDTS434N6.jpeg',
                'created_at' => '2025-08-22 09:50:26',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 29,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-488201',
                'nama_alat' => 'Tangga Teleskopik',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '7,2 meter',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDB6TS9N0KTYMSEPXQK312.jpg',
                'created_at' => '2025-08-22 09:51:07',
                'updated_at' => '2025-08-28 06:19:47',
            ],
            [
                'id' => 30,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-553152',
                'nama_alat' => 'Box Peralatan (Mvp)',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => 'armada roda 4 / mvp',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:52:09',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 31,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-838123',
                'nama_alat' => 'Box Peralatan (PickUp)',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => 'roda 4 pickup',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:52:48',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 32,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-424778',
                'nama_alat' => 'Katrol',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => 'kapasitas 2 ton',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDFV4VK32ZFPTYTPN47E8R.jpg',
                'created_at' => '2025-08-22 09:53:22',
                'updated_at' => '2025-08-28 06:22:19',
            ],
            [
                'id' => 33,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-514374',
                'nama_alat' => 'Rubber Insulating Boots',
                'kategori_alat' => 'proteksi',
                'merek_alat' => '-',
                'spesifikasi' => 'class 3 medium voltage',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:54:36',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 34,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-435858',
                'nama_alat' => 'Voltage Detector',
                'kategori_alat' => 'pengukuran',
                'merek_alat' => '-',
                'spesifikasi' => '20kV',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:55:19',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 35,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-114045',
                'nama_alat' => 'Log out',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:55:58',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 36,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-586555',
                'nama_alat' => 'Tag out',
                'kategori_alat' => 'pendukung',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 09:56:16',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 37,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-960280',
                'nama_alat' => 'Papan Peringatan',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => 'papan peringatan ada kegiatan',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RCYX7AJS6NBMF3445CH04E.jpg',
                'created_at' => '2025-08-22 09:56:45',
                'updated_at' => '2025-08-28 06:13:04',
            ],
            [
                'id' => 38,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-508593',
                'nama_alat' => 'Cone',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RCY31WKGJDF5RNE33X07E3.jpg',
                'created_at' => '2025-08-22 09:57:13',
                'updated_at' => '2025-08-28 06:12:37',
            ],
            [
                'id' => 39,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-385057',
                'nama_alat' => 'Rantai Cone',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDF97YAJHZ3SV5RQ0XT0N2.jpg',
                'created_at' => '2025-08-22 09:57:41',
                'updated_at' => '2025-08-28 06:22:01',
            ],
            [
                'id' => 40,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-181173',
                'nama_alat' => 'Tas P3K',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RCZMMM95N4GWWQ0YN10MRR.jpg',
                'created_at' => '2025-08-22 09:58:15',
                'updated_at' => '2025-08-28 06:13:28',
            ],
            [
                'id' => 41,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-580765',
                'nama_alat' => 'APAR',
                'kategori_alat' => 'pemeliharaan',
                'merek_alat' => '-',
                'spesifikasi' => '1kg (dry powder)',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RD0AWG0XHR0424PD1QB291.jpg',
                'created_at' => '2025-08-22 09:58:57',
                'updated_at' => '2025-08-28 06:13:51',
            ],
            [
                'id' => 42,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-928530',
                'nama_alat' => 'Rubber Insulating Gloves',
                'kategori_alat' => 'proteksi',
                'merek_alat' => '-',
                'spesifikasi' => 'class 3 30kv/3menit/max use voltage 26.500 volt',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 10:00:42',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 43,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-350380',
                'nama_alat' => 'Sepatu Boots',
                'kategori_alat' => 'proteksi',
                'merek_alat' => '-',
                'spesifikasi' => 'Sepatu boots tahan bentur',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDH0D6M2FWWEKFC5JVX8ZA.jpg',
                'created_at' => '2025-08-22 10:01:14',
                'updated_at' => '2025-08-28 06:22:57',
            ],
            [
                'id' => 44,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-329904',
                'nama_alat' => 'Full Body Harnest',
                'kategori_alat' => 'proteksi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDKFWDN9BG9F825ZSQPD3X.jpg',
                'created_at' => '2025-08-22 10:01:59',
                'updated_at' => '2025-08-28 06:24:18',
            ],
            [
                'id' => 45,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-411762',
                'nama_alat' => 'Lock Lanyard',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDN5DEMPTWD6VH2NF63F8E.jpg',
                'created_at' => '2025-08-22 10:02:31',
                'updated_at' => '2025-08-28 06:25:13',
            ],
            [
                'id' => 46,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-491907',
                'nama_alat' => 'Sarung Tangan 500V',
                'kategori_alat' => 'proteksi',
                'merek_alat' => '-',
                'spesifikasi' => '500v',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => '01K3RDHQXX7YKWMQFPGH6MB90E.jpg',
                'created_at' => '2025-08-22 10:03:23',
                'updated_at' => '2025-08-28 06:23:21',
            ],
            [
                'id' => 47,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-261793',
                'nama_alat' => 'GPS',
                'kategori_alat' => 'pengukuran',
                'merek_alat' => '-',
                'spesifikasi' => '-',
                'tanggal_masuk' => '2025-08-23',
                'status_alat' => 'Baik',
                'foto' => null,
                'created_at' => '2025-08-22 10:03:48',
                'updated_at' => '2025-08-28 05:46:58',
            ],
            [
                'id' => 48,
                'mobil_id' => 1,
                'kode_barcode' => 'QR-343178',
                'nama_alat' => 'Tali Tambang',
                'kategori_alat' => 'distribusi',
                'merek_alat' => '-',
                'spesifikasi' => 'Tali Tambang Manila 12 mm2 (U/ikat',
                'tanggal_masuk' => '2025-08-28',
                'status_alat' => 'Baik',
                'foto' => '01K3R9G65QM5S0D6YRF723GZM5.jpg',
                'created_at' => '2025-08-28 05:05:53',
                'updated_at' => '2025-08-28 05:46:58',
            ],
        ];

        foreach ($alats as $alat) {
            Alat::create($alat);
        }
    }
}
